// Package article provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package article

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /articles)
	GetArticles(ctx echo.Context, params GetArticlesParams) error

	// (POST /articles)
	PostArticle(ctx echo.Context) error

	// (DELETE /articles/{id})
	DeleteArticle(ctx echo.Context, id int64) error

	// (GET /articles/{id})
	GetArticle(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetArticles converts echo context to params.
func (w *ServerInterfaceWrapper) GetArticles(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesParams
	// ------------- Optional query parameter "feeds" -------------

	err = runtime.BindQueryParameter("form", true, false, "feeds", ctx.QueryParams(), &params.Feeds)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter feeds: %s", err))
	}

	// ------------- Optional query parameter "categories" -------------

	err = runtime.BindQueryParameter("form", true, false, "categories", ctx.QueryParams(), &params.Categories)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categories: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArticles(ctx, params)
	return err
}

// PostArticle converts echo context to params.
func (w *ServerInterfaceWrapper) PostArticle(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostArticle(ctx)
	return err
}

// DeleteArticle converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteArticle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteArticle(ctx, id)
	return err
}

// GetArticle converts echo context to params.
func (w *ServerInterfaceWrapper) GetArticle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArticle(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/articles", wrapper.GetArticles)
	router.POST(baseURL+"/articles", wrapper.PostArticle)
	router.DELETE(baseURL+"/articles/:id", wrapper.DeleteArticle)
	router.GET(baseURL+"/articles/:id", wrapper.GetArticle)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTW/cNhD9K4NJLwUEr5sEPejmdIt2gaINitwco+BKoxUTiVQ4I9uLhf57MeRqPyzF",
	"iZseDOQiidKQ82be46N2WPi2846cMOY75KKm1sTHqyC2aEgfTdP8VWF+vcMfAlWY44vFcdpiP2fxJ92N",
	"c4bs8dB93D9p4eFmyPD8Vb7DLviOgliKaGyp18qH1gjmaJ38/BozlG1HaUgbCjgMGQb61NtAJebXOuvm",
	"EOTXH6gQHDL8NQQfpjkKX9LDLK9ezmTJsCVms4nR+48swbrNBEFc8xg/h+akb/kO6d60XXosjNDGh4ju",
	"+nSUnQ5uMqxIk6Vbhl2/bizXVC6NaKbzcYZ9aDCP1yF72IGTjDu0Qi3PlHiowYRgtjpOAGYCH2CZiYho",
	"vtRFDZq2TqOsq7zOL4mLYDux3qnoXsCVg6u3K5DaCDQkDEXP4lsKDMpjMIXAnZUa/rDuI4NxJZjEAr93",
	"72rLwLXvmxLWBAbWJEIBirp3H8FXUPqib8mJ0YTw7s3vkP/43qlUrCh5o5xZQWCGtxQ4Qfvp4vLiUgv3",
	"HTnTWczxVXyVYWekjv1ejEh0sCGZFvg3SR8cg2maE9gYVw0R1EoV8RvJCCSuH0xLQoHjXj5fUSlkEA+V",
	"bbTU9RYzpPuuiZtCQk/abMzxU09BvznT0jgPs71zPE02LNvYLN1w0TPOIR3V+B9wnW2Xbwd3o4LkzjtO",
	"rLy8vEyW4YRcJMh0XWOL2PvFB9YCdnN5v8IWp2hU6ee9GUmHERXGkMr0jTwJ2GN4kk/OZO8d3XdUCJVA",
	"x5jO84xUfwlkhBgMOLobxQrWgdQELD7QBSz7BFHDAqmq/V30snM5v/U86hmTQRDLG19u/7eKT8+wadn7",
	"T6pGU5Z6O9SAp4alqhy+UTBfpZPP6uL5yGLIjna22NlySAppKJ0H5wuk96oVtm7T0EEua8NUgk+iWS2B",
	"e0U/I5FlXOEokkc9b7VULzdHVve4TgymMg2PDqP+fDQYW044PzWaL/6qHB2GbTzxZzzm9bRFI9oEtXwG",
	"2/7xA8pNOTywu1pmYKvIac8UoPTE4LxAbW4JTFEQ87jLzIHSzx1xT2a7Iinq50P2d+oP2hsKtyNn6e+0",
	"FunyxWL/M3xReD2Ch38DAAD//06udE+uDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

