// Package article provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package article

// Article defines model for Article.
type Article struct {
	// Embedded struct due to allOf(#/components/schemas/NewArticle)
	NewArticle `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/Article_allOf)
	ArticleAllOf `yaml:",inline"`
}

// ArticleAllOf defines model for Article_allOf.
type ArticleAllOf struct {
	Id int64 `json:"id"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewArticle defines model for NewArticle.
type NewArticle struct {
	Categories    *[]string `json:"categories,omitempty"`
	Feed          *string   `json:"feed,omitempty"`
	PublishedDate *string   `json:"publishedDate,omitempty"`
	Url           string    `json:"url"`
}

// GetArticlesParams defines parameters for GetArticles.
type GetArticlesParams struct {
	// feeds to filter by
	Feeds *[]string `json:"feeds,omitempty"`

	// categories to filter by
	Categories *[]string `json:"categories,omitempty"`
}

// PostArticleJSONBody defines parameters for PostArticle.
type PostArticleJSONBody NewArticle

// PostArticleJSONRequestBody defines body for PostArticle for application/json ContentType.
type PostArticleJSONRequestBody PostArticleJSONBody

