// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /articles)
	GetArticles(ctx echo.Context, params GetArticlesParams) error

	// (POST /articles)
	PostArticle(ctx echo.Context) error

	// (DELETE /articles/{id})
	DeleteArticle(ctx echo.Context, id int64) error

	// (GET /articles/{id})
	GetArticle(ctx echo.Context, id int64) error

	// (GET /feeds)
	GetFeeds(ctx echo.Context) error

	// (POST /feeds)
	PostFeed(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetArticles converts echo context to params.
func (w *ServerInterfaceWrapper) GetArticles(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesParams
	// ------------- Optional query parameter "feedIDs" -------------

	err = runtime.BindQueryParameter("form", true, false, "feedIDs", ctx.QueryParams(), &params.FeedIDs)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter feedIDs: %s", err))
	}

	// ------------- Optional query parameter "categories" -------------

	err = runtime.BindQueryParameter("form", true, false, "categories", ctx.QueryParams(), &params.Categories)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categories: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArticles(ctx, params)
	return err
}

// PostArticle converts echo context to params.
func (w *ServerInterfaceWrapper) PostArticle(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostArticle(ctx)
	return err
}

// DeleteArticle converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteArticle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteArticle(ctx, id)
	return err
}

// GetArticle converts echo context to params.
func (w *ServerInterfaceWrapper) GetArticle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetArticle(ctx, id)
	return err
}

// GetFeeds converts echo context to params.
func (w *ServerInterfaceWrapper) GetFeeds(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFeeds(ctx)
	return err
}

// PostFeed converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeed(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFeed(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/articles", wrapper.GetArticles)
	router.POST(baseURL+"/articles", wrapper.PostArticle)
	router.DELETE(baseURL+"/articles/:id", wrapper.DeleteArticle)
	router.GET(baseURL+"/articles/:id", wrapper.GetArticle)
	router.GET(baseURL+"/feeds", wrapper.GetFeeds)
	router.POST(baseURL+"/feeds", wrapper.PostFeed)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RXUW/bNhD+Kwd2wDBAsNO02IPe0nnZDAxLMeQtNQZaOllsJVIlT0kMQ/99ONKypEiJ",
	"na3dMvTFFqXj3Xd3n76jdiIxZWU0anIi3gmX5FhKf3lhSSUF8qUsiqtMxDc78Z3FTMTi1bzbNt/vmf+O",
	"d+2eJnradG/3Z3DcrJpIDG/FO1FZU6ElhR6NSvk3M7aUJGKhNP34VkSCthWGJW7QiqaJhMXPtbKYiviG",
	"d60ORmb9ERMSTSR+ttbYcYzEpPgwypvziSiRKNE5ufHW+4eOrNKbEQLvs7OfQnOJmD6ryn7DsRKzUb++",
	"vfXXLW6PBvFO4L0sq3CZSMKNsT7mTX8V9RerSGS+IOEvElW9LpTLMV1I4kjDdSRqW4jY/zbRw4b2Iu6E",
	"IizdRMcOOUhr5ZbXHHl5Wk1G+Cbce4THiMJGh8iP1LVlyrGibl93Nd2es7dQpP2+WWLKL1esk7MbJ8VW",
	"SmeG96foEqsqUkYzpV/BhYaL90ugXBIUSA6S2pEp0Trg6luZENwpyuE3pT85kDoFGXjnPujrXDlwuamL",
	"FNYIEtZIhBaSvNafwGSQmqQuUZPkgHD97leIf/igucGKuLKtHjkGISJxi9YFaK9nZ7MzTtxUqGWlRCze",
	"+FuRqCTlvmjzFgkvNkjjBP9Aqq12IIuiB1t4r9aDYgKKX5BaIN6/lSUSWudlYuiRqeOADGSq4FTXWxEJ",
	"vK8Kr2pka+Rii1h8rtHyMy1L3O9bLth9kI5B90/g/0M+ONr6AvJWr1JDmB3N/gbWgWhMwD1K1iG4FZPU",
	"VUa70Knzs7MwBzSh9k2TVVWoxPdj/tFxArupuCfMujEaZv+wNi0RoEUlvEkm64KeBewpPGH4TUSvNd5X",
	"mBCmgJ1NZdwEfX+yKAkdSNB41xIYlAbKERwZizNY1AEim1lkpps7r+hDir83ruW4CKKBjt6ZdPvFMu4f",
	"TMZp7x8xG2Wa8t8hB9EXMWZl8w8JcxJPHuXFy6FFE3USN9+ptAkMKTBMwKGDcJ+54pTeFHigy1o6TMEE",
	"0iwX4GpGP0GRhffQkeRJHVwuWN9l19U9rp7AZLJwrcKwZncCo9JRz/tCc4IctgrjlB/RExrzdlyiFm2A",
	"mr6A1/7poaXHPTx0d7mIQGW+p7VDC6lBB9oQ5PIWQSYJOte+ZfLQ0sfG3rO7nSEl+ctp9rerD/48ctL5",
	"x1tOH34uvZN/Y0zvP6qOzmiP6P82oAPoU8Yz4C2ymak3OVtvobJmLdfFdn+c1t8TrHEG/oStOMD11eJq",
	"NjnWL8MX3Fea6aFj0x36z6f5Y+CY6y/oPWUNQ3vbamv4TMyJqng+H3wtrpq/AgAA//+28U19KxIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

