// Package feed provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package feed

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /feeds)
	GetFeeds(ctx echo.Context) error

	// (POST /feeds)
	PostFeed(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFeeds converts echo context to params.
func (w *ServerInterfaceWrapper) GetFeeds(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFeeds(ctx)
	return err
}

// PostFeed converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeed(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostFeed(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/feeds", wrapper.GetFeeds)
	router.POST(baseURL+"/feeds", wrapper.PostFeed)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVT2/bPgz9KgT7A34YECRpO+zgW7uuW4FhLYbe2mJQZCZWa0saRTcNAn/3gXKS/knQ",
	"YtgOO1mynx4f+Uh5iTY0MXjykrBYYrIVNSYvPzEH1kXkEInFUX5tQ0n6nAZujGCBzsvhAQ5QFpH6Lc2I",
	"sRtgQymZWUavPiZh52fYdQNk+tk6phKLq57zEX+zIQuTW7KiXKek0CWauj6fYnG1xP+Ypljg3ugxg9FK",
	"/ugbzfOBbvA6TkE/esruZhVltd9K3JUv0/7wfkfaL1Jz5c501gKLJdKDaWKdq2SN0CxwDni13i32cbBZ",
	"HyhbyzUW63NDGxplfOHSE6YlOqEm7bBhI8wwm4XuM/VbdiloOylFOT8Ner6kZNlFccFr6ffgyMPRxRlI",
	"ZQRqkgS2TRIa4gRaOTZWYO6kgq/O3yUwvgTD4mxN6dpfVi5BqkJblzAhMDAhEWKwVevvIEyhDLZtyIvR",
	"gHB5/AWKd9dezXGilcWjFZeKwAHeE6de2v5wPBxr4iGSN9FhgYf51QCjkSoXbTQlKvNqRrKd3XeSln0C",
	"U9eQkTmympHlnJVY4GeS00yihUwx+NQbczAe9zPlhXzmNjHWzuaTo9ukAdZD+czIt5p621u157nwrAjW",
	"ejB/n5q2lt+S9JqS/grZEbr19BDJCpVAj5gY0o76fmQyQgkMeJpDL9p5kIogSWAawknbC1QQkxoR5sp8",
	"TwoL7axS9AIih4mZ1ItVL/n/BSY0hNxeTgNcnp+cD7fMuwgpu4f9FFCS41Au/lqRNnfVbodAApgyPzYp",
	"49N5FG6p+8O+erudtsVpr/873aOoRKyTnf8O/R1ZicRiNHp2Vd50vwIAAP//ftEvEPUGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

