openapi: 3.0.0
info:
  description: |
    ## An API that lets customers interact with Links and articles
    This should be a better chunk of documentation TBH :)
  title: Articles API
  version: 1.0.0
servers:
- url: http://example.com
paths:
  /feeds:
    get:
      description: |
        Returns all feeds
      operationId: getFeeds
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Feed'
                type: array
          description: Feeds response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
    post:
      description: Creates a new Feeds in the store. Duplicates are allowed even though they probably shouldn't be. This is a TODO.
      operationId: post feed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewFeed'
        description: Feed to add to the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
          description: feed response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
components:
  schemas:
    Feed:
      allOf:
      - $ref: '#/components/schemas/NewFeed'
      - $ref: '#/components/schemas/Feed_allOf'
    NewFeed:
      example:
        url: example.com
        categories:
        - category1
        - category2
      properties:
        url:
          type: string
        categories:
          items:
            type: string
          type: array
      required:
      - url
      type: object
    Feed_allOf:
      properties:
        id:
          format: int64
          type: integer
      required:
      - id
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
